# TODO
baseURL = "http://limbostray.github.io/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Horel's Blog"
# 启用符号表情
enableEmoji = true
# Lastmod使用该内容文件的最后一个 git 提交日期更新每个页面的参数
enableGitInfo = true
# 搜索引擎不收录
enableRobotsTXT = true

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FeelIt"

[params]
  # FeelIt 主题版本
  version = "1.0.X"
  # 网站描述
  description = "Welcome to Horel's blog."
  # 网站关键词
  keywords = ["Linux", "C/C++", "Computer Graphics"]
  # 网站默认主题样式 ("light", "dark", "auto")
  defaultTheme = "auto"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
# TODO
  gitRepo = "https://github.com/limbostray/limbostray.github.io.git"
  # FeelIt 新增 | 0.1.1
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ("sha256", "sha384", "sha512", "md5")
  fingerprint = "sha256"
  # FeelIt 新增 | 0.2.0
  # 日期格式
  dateFormat = "2006-01-02"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  #images = ["/logo.png"]
  # FeelIt 新增 | 1.0.0
  # 是否启用 CSS 和 JS 源映射
  SourceMap = true

 # FeelIt 新增 | 1.0.1
 # PWA config
  [params.pwa]
    # whether to enable PWA support
    enable = true
    # service-worker version
    version = "1.0.1"

  # FeelIt 新增 | 0.2.0
  # 应用图标配置
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "Horel's Blog"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
# TODO
    svgFavicon = ""
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10磁贴颜色
    tileColor = "#da532c"

# FeelIt 新增 | 0.2.0
  # 搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ("lunr", "algolia")
    type = "algolia"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # FeelIt 新增 | 0.2.1
    # 最大结果数目
    maxResultLength = 10
    # FeelIt 新增 | 0.2.3
    # 结果内容片段长度
    snippetLength = 50
    # FeelIt 新增 | 0.2.1
    # 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # FeelIt 新增 | 0.2.4
    # 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
# TODO
    [params.search.algolia]
      index = "horel_io"
      appID = "JLSXOSCBYN"
      searchKey = "44c6685d5b1572458f71fa76f52cff67"

  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "auto"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"

 # 页面底部信息配置
  [params.footer]
    enable = true
    # FeelIt 新增 | 0.2.0
    # 自定义内容 (支持 HTML 格式)
    custom = ''
    # FeelIt 新增 | 0.2.0
    # 是否显示 Hugo 和主题信息
    hugo = true
    # FeelIt 新增 | 0.2.0
    # 是否显示版权信息
    copyright = true
    # FeelIt 新增 | 0.2.0
    # 是否显示作者
    author = true
    # 网站创立年份
    since = 2020
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # 许可协议信息 (支持 HTML 格式)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# FeelIt 新增 | 0.2.0
# Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # FeelIt 新增 | 0.2.0
  # List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 25
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 20

# 关于页面配置
  [params.about]
    # 是否启用关于页面的配置文件
    # 依赖于取决于 .Site.Params.home.profile.enable
    enable = true
    # 是否启用参数布局
    param = true
    # 参数布局的标题
    paramTitle = "Personal Information"
    # 您网站的一般描述
    # 可以用markdown样式写
    description = "<h1>This&#39;s Horel&#39;s Official Blog.</h1><p>Mainly about Computer Graphics, C/C++ and Linux.</p><p>Welcome to exchange technology with me.</p><p>You can find my essays about anime and games on this <a href=\"https://horel.github.io\">unofficial blog</a>.</p>"
    # 你的状态描述
    [[params.about.status]]
      faIcon = "fas fa-building"
      title = "School"
      desc = "DLUT"
    [[params.about.status]]
      faIcon = "fas fa-briefcase fa-fw"
      title = "Career"
      desc = "Undergraduate"
    [[params.about.status]]
      title = "Location"
      faIcon = "fas fa-map-marker-alt"
      desc = "Dalian"
    # 参数说明
    [[params.about.parameter]]
      language = "Computer Graphics"
      level = "30"
    [[params.about.parameter]]
      language = "C/C++"
      level = "60"
    [[params.about.parameter]]
      language = "Linux"
      level = "40"

 # 主页配置
  [params.home]
    # FeelIt 新增 | 0.2.0
    # RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # 主页显示头像的 URL
# TODO
      avatarURL = "https://tva4.sinaimg.cn/large/008ieO5lly8h1itddxtf1j30e80e8gmp.jpg"
      # FeelIt 更改 | 0.2.7
      # 主页显示的网站副标题
      subtitle = "= Siege Lions are not engineers. ="
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # FeelIt 新增 | 0.2.0
      # 免责声明 (支持 HTML 格式)
      disclaimer = "There is a crack in everything , that's how the light gets in ."
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 10
      # FeelIt 更改 | 1.0.1
      # display image-preview
# TODO
      imagePreview = false
      # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false

# 作者的社交信息设置
  [params.social]
    GitHub = "horel"
    Telegram = "gapcolt"
    Zhihu = "lan-an-53-95"
    Bilibili = "355396694"
    Email = "1494255412@mail.dlut.edu.cn"
    RSS = true # FeelIt 新增 | 0.2.0

 # FeelIt 更改 | 0.2.0
 # 文章页面配置
  [params.page]
    # FeelIt 新增 | 0.2.0
 # 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # FeelIt 新增 | 0.2.0
 # 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # FeelIt 新增 | 0.2.0
 # 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # FeelIt 新增 | 0.2.0
 # 是否使用 ruby 扩展语法
    ruby = true
    # FeelIt 新增 | 0.2.0
 # 是否使用 fraction 扩展语法
    fraction = true
    # FeelIt 新增 | 0.2.0
 # 是否使用 fontawesome 扩展语法
    fontawesome = true
    # FeelIt 新增 | 1.0.0
 # 是否使用 fontawesome 作为CDN源
    cdnfontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # FeelIt 新增 | 0.2.4
 # 是否在 RSS 中显示全文内容
    rssFullText = true
    # FeelIt 新增 | 0.2.0
# 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # 是否使侧边目录自动折叠展开
      auto = true
    # FeelIt 新增 | 0.2.0
# 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 10
   # FeelIt 更改 | 0.2.0
# KaTeX 数学公式
    [params.page.math]
      enable = true
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true

# 页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

 # FeelIt 新增 | 0.2.10
 # 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""

 # FeelIt 新增 | 0.2.5
 # TypeIt 配置
  [params.typeit]
    # 每一步的打字速度 (单位是毫秒)
    speed = 100
    # 光标的闪烁速度 (单位是毫秒)
    cursorSpeed = 1000
    # 光标的字符 (支持 HTML 格式)
    cursorChar = "|"
    # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
    duration = -1

# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

 # FeelIt 更改 | 1.0.1
 # 网站分析配置
  [params.analytics]
    enable = false
    # FeelIt 删除 | 1.0.0
 # Google Analytics 相关隐私 (被 privacy.googleAnalytics 替代)
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""
    # FeelIt 新增 | 1.0.1
 # GoatCounter Analytics
    [params.analytics.goatcounter]
      # GoatCounter code
      code = ""

[params.cookieconsent]
  enable = false
  [params.cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

  # FeelIt 新增 | 0.2.8
  # 兼容性设置
  [params.compatibility]
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

# 作者配置
[author]
  name = "Horel"
  email = "1494255412@mail.dlut.edu.cn"
  link = "https://github.com/horel"

[menu]
  [[menu.main]]
    identifier = "main"
    pre = ""
    post = ""
    name = "主页"
    url = "/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 5

# TODO
[languages]
  [languages.zh-cn]
    weight = 1
    # 网站语言, 仅在这里 CN 大写
    languageCode = "zh-CN"
    languageName = "简体中文"
  [languages.en]
    weight = 2
    languageCode = "en"
    languageName = "English"
  [[languages.en.menu.main]]
    identifier = "main"
    pre = ""
    post = ""
    name = "Main"
    url = "/"
    title = ""
    weight = 1
  [[languages.en.menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "Posts"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 2
  [[languages.en.menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 3
  [[languages.en.menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 4
  [[languages.en.menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 5



# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  [markup.tableOfContents]
    ordered = false
    startLevel = 1
    endLevel = 6

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = "posts/:filename"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
